from __future__ import annotations

GLOBAL_INDEX_FILE_NAME: str = "project_index.toml"
GLOBAL_STATE_DIRECTORY_NAME: str = "dev-tools"
LINUX_STATE_ENVIRONMENT_VARIABLE_NAME: str = "XDG_STATE_HOME"
LOCAL_APPLICATION_DATA_ENVIRONMENT_VARIABLE_NAME: str = "LOCALAPPDATA"
POLICY_MANIFEST_FILE_NAME: str = "policy_manifest.toml"
POLICY_MANIFEST_VERSION: int = 1
PROJECT_INDEX_VERSION: int = 1
