VSCODE_APPLICATION_DIRECTORY_NAME = "Code"
VSCODE_USER_DIRECTORY_NAME = "User"
VSCODE_SETTINGS_FILE_NAME = "settings.json"
VSCODE_USER_SETTINGS_DISPLAY_PATH = "VS Code user settings"

VSCODE_FILES_EXCLUDE_SETTING_NAME = "files.exclude"
VSCODE_GLOBAL_FILES_EXCLUDE_PATTERNS: tuple[str, ...] = (
    "**/__pycache__",
    "**/.pytest_cache",
    "**/.mypy_cache",
    "**/.ruff_cache",
)

WINDOWS_APPLICATION_DATA_ENVIRONMENT_VARIABLE_NAME = "APPDATA"
WINDOWS_FALLBACK_APPLICATION_DATA_PATH_PARTS: tuple[str, ...] = (
    "AppData",
    "Roaming",
)
MACOS_CONFIGURATION_PATH_PARTS: tuple[str, ...] = (
    "Library",
    "Application Support",
)
LINUX_CONFIGURATION_ENVIRONMENT_VARIABLE_NAME = "XDG_CONFIG_HOME"
LINUX_FALLBACK_CONFIGURATION_DIRECTORY_NAME = ".config"

POLICY_GITIGNORE_MANAGED_BLOCK_ID = "gitignore.managed_block.common_local_artifacts"
POLICY_GITIGNORE_MANAGED_BLOCK_REVISION = 1
POLICY_VSCODE_WORKSPACE_SETTINGS_ID = "vscode.settings.workspace_defaults"
POLICY_VSCODE_WORKSPACE_SETTINGS_REVISION = 1
POLICY_VSCODE_EXTENSIONS_ID = "vscode.extensions.recommended_tools"
POLICY_VSCODE_EXTENSIONS_REVISION = 1
POLICY_VSCODE_USER_FILES_EXCLUDE_ID = "vscode.user_settings.files_exclude"
POLICY_VSCODE_USER_FILES_EXCLUDE_REVISION = 1
POLICY_PYRIGHT_CONFIG_ID = "pyright.config.python_type_checking"
POLICY_PYRIGHT_CONFIG_REVISION = 1
POLICY_PYPROJECT_DEFAULTS_ID = "pyproject.uv_python_tooling_defaults"
POLICY_PYPROJECT_DEFAULTS_REVISION = 1
POLICY_PACKAGE_JSON_ID = "package_json.typescript_tooling_defaults"
POLICY_PACKAGE_JSON_REVISION = 1
POLICY_TSCONFIG_ID = "tsconfig.strict_typescript_defaults"
POLICY_TSCONFIG_REVISION = 1
POLICY_PRETTIER_CONFIG_ID = "prettier.config.defaults"
POLICY_PRETTIER_CONFIG_REVISION = 1
