VSCODE_APPLICATION_DIRECTORY_NAME = "Code"
VSCODE_USER_DIRECTORY_NAME = "User"
VSCODE_SETTINGS_FILE_NAME = "settings.json"
VSCODE_USER_SETTINGS_DISPLAY_PATH = "VS Code user settings"

VSCODE_FILES_EXCLUDE_SETTING_NAME = "files.exclude"
VSCODE_GLOBAL_FILES_EXCLUDE_PATTERNS: tuple[str, ...] = (
    "**/__pycache__",
    "**/.pytest_cache",
    "**/.mypy_cache",
    "**/.ruff_cache",
)

WINDOWS_APPLICATION_DATA_ENVIRONMENT_VARIABLE_NAME = "APPDATA"
WINDOWS_FALLBACK_APPLICATION_DATA_PATH_PARTS: tuple[str, ...] = (
    "AppData",
    "Roaming",
)
MACOS_CONFIGURATION_PATH_PARTS: tuple[str, ...] = (
    "Library",
    "Application Support",
)
LINUX_CONFIGURATION_ENVIRONMENT_VARIABLE_NAME = "XDG_CONFIG_HOME"
LINUX_FALLBACK_CONFIGURATION_DIRECTORY_NAME = ".config"
